name: build

on:
  workflow_dispatch:
    inputs:
      rust-version:
        description: 'The version of rust'
        required: true
        default: '1.81.0'
      tauri-cli-version:
        description: 'The version of tauri-cli'
        required: true
        default: '2.0.3'
      node-version:
        description: 'The version of node'
        required: true
        default: '20.18.0'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm
          push: true
          build-args: |
            TAURI_CLI_VERSION=${{ github.event.inputs.tauri-cli-version }}
            RUST_VERSION=${{ github.event.inputs.rust-version }}
            NODE_VERSION_INSTALL=${{ github.event.inputs.node-version }}
          tags: liudonghua123/tauri-build:${{ github.event.inputs.tauri-cli-version }}-rust-${{ github.event.inputs.rust-version }}-node-${{ github.event.inputs.node-version }},liudonghua123/tauri-build:latest